version: "3"

services:
  #  nginx:
  #    image: nginx:latest
  #    container_name: nginx
  #    ports:
  #      - 443:443
  #    volumes:
  #      - ./opt/nginx/yourhost.xyz.key:/etc/nginx/yourhost.xyz.key:ro
  #      - ./opt/nginx/yourhost.xyz.crt:/etc/nginx/yourhost.xyz.crt:ro
  #      - ./opt/nginx/sonarqube.conf:/etc/nginx/conf.d/sonarqube.conf:z
  #    networks:
  #      - cicdnet
  #    restart: always

  nexus3:
    build: ./build/nexus
    restart: always
    user: root
    container_name: nexus3
    networks:
      - cicdnet
    ports:
      - 8081:8081
    volumes:
      - ./opt/nexus/nexus-data:/nexus-data
      - ./opt/nexus/sonatype-work:/sonatype-work
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"

  jenkins:
    build: ./build/jenkins
    restart: always
    container_name: jenkins
    hostname: jenkins
    networks:
      - cicdnet
    privileged: true
    # user: root
    depends_on:
      - nexus3
      - sonarqube
    ports:
      - '8089:8080'
      - '50000:50000'
    environment:
      JAVA_OPTS: '-Djava.util.logging.config.file=./opt/jenkins/jenkins_home/log.properties'
    volumes:
      - ./opt/jenkins/jenkins_home:/var/jenkins_home
      - ./opt/jenkins/run/docker.sock:/var/run/docker.sock
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432

  database:
    build: ./build/postgresql
    restart: always
    container_name: postgresql
    networks:
      - cicdnet
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - ./opt/postgresql:/var/lib/postgresql:z
      - ./opt/postgresql/data:/var/lib/postgresql/data:z

  sonarqube:
    build: ./build/sonarqube
    restart: always
    container_name: sonarqube
    hostname: sonarqube
    networks:
      - cicdnet
    depends_on:
      - database
    ports:
      - 9000:9000
      - 9001:9001
      - 9092:9092
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx2048m
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://database:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://database:5432/sonarqube
    volumes:
      - ./opt/sonarqube/conf:/opt/sonarqube/conf:z
      - ./opt/sonarqube/data:/opt/sonarqube/data:z
      - ./opt/sonarqube/logs:/opt/sonarqube/logs:z
      - ./opt/sonarqube/extensions/plugins:/opt/sonarqube/extensions/plugins:z
      - ./opt/sonarqube/extensions/downloads:/opt/sonarqube/extensions/downloads:z

networks:
  cicdnet:
    driver: bridge